# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6377b2792de17ec14f509ed595a7838ed1ed7e33bedb5f974f2146ebb9c08251971df844ac2ac45a1a1dfc9c04094bafa7cb04ba168f88ff7dfa1f3145490ce6

test:
  secret_key_base: 3ce1b94c60afe0811f546cf793cb577f6eb8bb13f31c3f3a2ab6a99971fc51f40995093f1271187169d10e14d0f2914f58b2f610d17de6cdb2de72771b117e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
